nome = str(input('digite seu nome completo:')).strip()
print('seu nome maiúsculo é {}'.format(nome.upper()))
print('seu nome minúsculo é {}'.format(nome.lower()))
print('seu nome possui {} letras'.format(len(nome) - nome.count(' ')))
#print('seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))